repos:
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.16.0"
    hooks:
      #-id: terraform-docs
      #- id: terraform_fmt
      - id: terraform-docs-go
        args: ["markdown", "table", "--output-file", "README.md", "."]
